### PR TITLE
Resiliency fix

### PR DESCRIPTION
**Pull request by maf23**
Added if-guards when getting length of certain run_status fields. This is needed because they may be nil if the chef run fails early enough. And this causes the length call to thrown and exception.

### CODE REVIEW

**Comment by imeyer** [comment]
@maf23 This is awesome, never experienced this edge case before. Do you think it may be better to test for `nil?`?

**Comment by maf23** [comment]
Unfortunately we encounter it all the time ;)

Leaving the test as it is or change it to be against nil is IMHO a matter of taste. I wrote the code as it is because that is shorter, but I don't have any strong opinions.

**Comment by imeyer** [comment]
@maf23 Awesome, works for me. Will cut a new version in a bit. :smile:

**Comment by imeyer** [comment]
@maf23 I just pushed `1.2.0` to rubygems, can you test that everything works as expected? I no longer have quick access to a graphite server. :frowning:

**Comment by maf23** [comment]
Thanks for the quick turnaround. I'm deploying it on our system now.

**Comment by maf23** [comment]
It works as expected. No more crashes in the handler and it sends over the
data it has.

**Pull request merged**
